branches:
  only:
    - master

install:
  - rm -rf public || exit 0

script:
  - cd src && ../binaries/hugo --theme=ghoust
  - pwd
  - ls
  - ls public

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
