# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ghoust"
license = "MIT"
description = ""
homepage = "https://github.com/hackerspaceshop/ghoust-website"
tags = ["blog", "company"]
features = ["blog", ]
min_version = 0.19

[author]
  name = "Chris Hager"
  homepage = "https://www.metachris.com"
